version: '3.8'

services:
  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env   # Reference the .env file for environment variables including Prisma's DATABASE_URL
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    command: ["npm", "run", "start"]