apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-fusion-order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pizza-fusion-order
  template:
    metadata:
      labels:
        app: pizza-fusion-order
    spec:
      containers:
      - name: pizza-fusion-order
        image: docker.io/docker380431/pizza-fusion-order-msc:latest
        ports:
        - containerPort: 3001