apiVersion: v1
kind: Service
metadata:
  name: pizza-fusion-order-service
spec:
  selector:
    app: pizza-fusion-order
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP